#!/bin/bash
#rosrun dvrk_robot dvrk_console_json -j /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ucb-dVRK/console-PSM1.json -i /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ros-io-PSM1.json

#rosrun dvrk_robot dvrk_console_json -j /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ucb-dVRK/console-PSM2.json -i /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ros-io-PSM2.json

rosrun dvrk_robot dvrk_console_json -j /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ucb-dVRK/console-PSM1-PSM2.json -i /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ros-io-PSM1.json -i /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ros-io-PSM2.json

# rosrun dvrk_robot dvrk_console_json -j /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ucb-dVRK/console-PSM1-PSM2-long.json -i /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ros-io-PSM1.json -i /home/davinci/catkin_ws/src/cisst-saw/sawIntuitiveResearchKit/share/ros-io-PSM2.json
